name: GNU/Linux

on:
  push:
    branches: [ master ]
    paths-ignore:
    - 'assets/'
    - 'dist/'
    - 'snap/'
    - 'Dockerfile'
    - 'LICENSE'
    - 'Makefile'
    - 'monolith.nuspec'
    - 'README.md'

jobs:
  build:

    strategy:
      matrix:
        os:
          - ubuntu-latest
        rust:
          - stable
    runs-on: ${{ matrix.os }}

    steps:
    - run: git config --global core.autocrlf false

    - uses: actions/checkout@v2

    - name: Build
      run: cargo build --all --locked --verbose
